name: Tests

on: push

jobs:
  main:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: ubuntu-latest, node-version: '24.2' }
          - { os: ubuntu-latest, node-version: latest }
          - { os: macos-latest, node-version: latest }
          - { os: windows-latest, node-version: latest }

    runs-on: ${{ matrix.os }}
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          cache: npm
          node-version: ${{ matrix.node-version }}

      - run: npm ci
      - run: npm run check
